"""Add user to Ticket

Revision ID: 08416a450110
Revises: 826728db1b8a
Create Date: 2025-12-22 06:07:58.309051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08416a450110'
down_revision = '826728db1b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['id_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
