"""Add menu_section to product

Revision ID: 40b3db75e496
Revises: f47bc7c93571
Create Date: 2025-12-21 17:59:20.823340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40b3db75e496'
down_revision = 'f47bc7c93571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_section', postgresql.ENUM('drinks', 'bar', 'grilled', name='menu_section_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('menu_section')

    # ### end Alembic commands ###
