"""Change to user and session models, to manage multiple sessions

Revision ID: 60b63fb5db52
Revises: 78741fb2cc00
Create Date: 2025-12-27 19:04:59.467406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b63fb5db52'
down_revision = '78741fb2cc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('session_id_user_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_session_id_user'), ['id_user'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_id_user'))
        batch_op.create_unique_constraint(batch_op.f('session_id_user_key'), ['id_user'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
