"""add_fk_constraints_fix_date_user_index

Revision ID: 6e17767eeec3
Revises: ebaa67f7e95e
Create Date: 2026-03-21 18:30:39.581629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e17767eeec3'
down_revision = 'ebaa67f7e95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'ticket', ['id_ticket'], ['id'])
    op.create_foreign_key(None, 'print_list_ticket', 'ticket', ['id_ticket'], ['id'])
    op.alter_column('ticket', 'operational_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.create_index('uq_user_username_active_only', 'user', ['username'], unique=True, postgresql_where='is_active = true')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_username_active_only', table_name='user', postgresql_where='is_active = true')
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('ticket', 'operational_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'print_list_ticket', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
