"""Add print_for_pay to Tickets and printed for Orders

Revision ID: 78741fb2cc00
Revises: 08416a450110
Create Date: 2025-12-23 06:16:44.624116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78741fb2cc00'
down_revision = '08416a450110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printed', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('print_list_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_for_pay', sa.Boolean(), nullable=False,server_default=sa.false()))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('printed', server_default=None)

    with op.batch_alter_table('print_list_ticket', schema=None) as batch_op:
        batch_op.alter_column('print_for_pay', server_default=None)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_list_ticket', schema=None) as batch_op:
        batch_op.drop_column('print_for_pay')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('printed')

    # ### end Alembic commands ###
