"""Change product_addons to not be in relation with a category

Revision ID: 826728db1b8a
Revises: c7f5c90af23b
Create Date: 2025-12-21 19:39:28.290369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826728db1b8a'
down_revision = 'c7f5c90af23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_addons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_addons_id_category_fkey'), type_='foreignkey')
        batch_op.drop_column('id_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_category', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('product_addons_id_category_fkey'), 'category', ['id_category'], ['id'])

    # ### end Alembic commands ###
