"""Change product addons relations with order

Revision ID: 99ae8e1feb10
Revises: fd78655e9d84
Create Date: 2025-12-06 22:31:56.780068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ae8e1feb10'
down_revision = 'fd78655e9d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_id_product_addon_fkey'), type_='foreignkey')
        batch_op.drop_column('id_product_addon')

    with op.batch_alter_table('product_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('ingredient_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_description', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_product_addon', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('order_id_product_addon_fkey'), 'product_addons', ['id_product_addon'], ['id'])

    # ### end Alembic commands ###
