"""Change  menu_section to Category

Revision ID: c7f5c90af23b
Revises: 40b3db75e496
Create Date: 2025-12-21 18:51:13.989375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7f5c90af23b'
down_revision = '40b3db75e496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_section', postgresql.ENUM('drinks', 'bar', 'grilled', name='menu_section_enum'), nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('menu_section')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_section', postgresql.ENUM('drinks', 'bar', 'grilled', name='menu_section_enum'), autoincrement=False, nullable=False))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('menu_section')

    # ### end Alembic commands ###
