"""Add client_name column to ticket

Revision ID: e44a7bd3d935
Revises: 60b63fb5db52
Create Date: 2026-01-02 01:39:53.059856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44a7bd3d935'
down_revision = '60b63fb5db52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
