"""Add display_name column to User

Revision ID: ebaa67f7e95e
Revises: 0e393e09eff0
Create Date: 2026-01-13 02:34:04.371275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebaa67f7e95e'
down_revision = '0e393e09eff0'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=True))

    op.execute("""
        UPDATE "user"
        SET display_name = username
        WHERE display_name IS NULL
    """)

    with op.batch_alter_table('user',schema=None) as batch_op:
        batch_op.alter_column(
            'display_name',
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###