"""Added is_paid column to ticket

Revision ID: f47bc7c93571
Revises: 99ae8e1feb10
Create Date: 2025-12-11 18:48:54.905906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47bc7c93571'
down_revision = '99ae8e1feb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
