"""Add source_addon and mirror_addon to let a product addon be in the menu as a product

Revision ID: f94390b8e1aa
Revises: e44a7bd3d935
Create Date: 2026-01-06 02:35:54.454840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94390b8e1aa'
down_revision = 'e44a7bd3d935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_source_addon', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_source_addon'])
        batch_op.create_foreign_key(None, 'product_addons', ['id_source_addon'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id_source_addon')

    # ### end Alembic commands ###
