"""Add ProductAddons table and change calc of totals in order

Revision ID: fd78655e9d84
Revises: b266b564c30c
Create Date: 2025-12-05 20:50:09.509030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd78655e9d84'
down_revision = 'b266b564c30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_description', sa.String(), nullable=False))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_product_addon', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'product_addons', ['id_product_addon'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_product_addon')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('ingredient_description')

    # ### end Alembic commands ###
