FROM python:3.12-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /api

RUN apt-get update && \
    apt-get install -y git make && \
    rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen --dev

COPY . .

ENV PYTHONPATH=/api:$PYTHONPATH